package templates

import (
	"os"
	"text/template"
)

func writePackageHeader(file *os.File, in PackageHeader) error {
	return template.Must(template.New("").Parse(PackageHeaderTemplate)).Execute(file, in)
}

type PackageHeader struct {
	Name string
}

var PackageHeaderTemplate = `// Code generated by go generate; DO NOT EDIT.

package {{.Name}}

import (
	"context"
	"database/sql"
)
`
